import Head from "next/head";
// import styles from "../styles/Home.module.css";
import Posts from "./posts";
// import * as globalConstants from "../utils/constants";

const Home = () => {
  // (() => {
  //   window.less
  //     .modifyVars({
  //       "@primary-color": globalConstants.PRIMARY_COLOR,
  //    // "@menu-bg": "",
  //     })
  //     .then(() => {
  //       console.log("color changed!");
  //     })
  //     .catch((error) => {
  //       console.error(error);
  //     });
  //   window.less.refreshStyles();
  // })();

  return (
    <div>
      <Head>
        <title>Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Posts />
      </main>
    </div>
  );
};

export default Home;
